apiVersion: v1
kind: Service
metadata:
  name: travel-apis-service
spec:
  type: NodePort
  selector:
    app: travel-apis
    project: voyage-capstone   
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000 
